### PR TITLE
Make startup faster

### PR DESCRIPTION
**Pull request by uRandomAlex**
Make startup faster by removing unnecessary check.

### CODE REVIEW

**Comment by bigdogmat** [comment]
Jesus...

**Comment by uRandomAlex** [comment]
@zerfgog My point is that we should care about ALL optimizations we can do. Of course, we should care about macro-optimizations more, but little micro-optimizations is cool too. Also, we should write perfomance-friendly code from start, so we don't have to "dive in the code" for micro-optimizations.

**Comment by bigdogmat** [comment]
Thank you for saving us that 1 nano second on start up

**Comment by FPtje** [comment]
I merged because of the style change. Not because of the optimisation. You
haven't understood Jack shit of what I said if you do this kind of shit for
optimisation reasons.

**Pull request merged**
